# (mandatory)
# Path to coverage profile file (output of `go test -coverprofile` command).
#
# For cases where there are many coverage profiles, such as when running
# unit tests and integration tests separately, you can combine all those
# profiles into one. In this case, the profile should have a comma-separated list
# of profile files, e.g., 'cover_unit.out,cover_integration.out'.
profile: cover.out

# (optional; but recommended to set)
# When specified reported file paths will not contain local prefix in the output.
local-prefix: 'github.com/pgvillage-tools/dbtwool'

# Holds coverage thresholds percentages, values should be in range [0-100].
threshold:
  # (optional; default 0)
  # Minimum coverage percentage required for individual files.
  #  file: 70
  file: 70

  # (optional; default 0)
  # Minimum coverage percentage required for each package.
  # package: 80
  package: 80

  # (optional; default 0)
  # Minimum overall project coverage percentage required.
  #  total: 80
  total: 4

# Holds regexp rules which will override thresholds for matched files or packages
# using their paths.
#
# First rule from this list that matches file or package is going to apply
# new threshold to it. If project has multiple rules that match same path,
# override rules should be listed in order from specific to more general rules.
override:
  # Increase coverage threshold to 100% for `foo` package
  # (default is 80, as configured above in this example).
  #- path: ^pkg/lib/foo$
  #  threshold: 100
  - path: ^pkg/db2client/client.go$
    threshold: 0.0
  - path: ^pkg/db2client/connection.go$
    threshold: 0.0
  - path: ^pkg/db2client/db2connparams.go$
    threshold: 0.0
  - path: ^pkg/db2client/pgconnparams.go$
    threshold: 0.0
  - path: ^pkg/db2client/pool.go$
    threshold: 0.0
  - path: ^pkg/db2client/queryhelper.go$
    threshold: 0.0
  - path: ^pkg/db2client/rdbms.go$
    threshold: 0.0
  - path: ^pkg/utils/main.go$
    threshold: 68
  - path: ^internal/arguments/args.go$
    threshold: 0.0
  - path: ^internal/arguments/handlers.go$
    threshold: 0.0
  - path: ^internal/arguments/type_enum.go$
    threshold: 0.0
  - path: ^internal/arguments/utils.go$
    threshold: 0.0
  - path: ^pkg/db2client/isolationlevel.go$
    threshold: 0.0
  - path: ^pkg/dbinterface/consistency.go$
    threshold: 0.0
  - path: ^pkg/pg/client.go$
    threshold: 0.0
  - path: ^pkg/pg/connection.go$
    threshold: 25
  - path: ^pkg/dbclient/rdbms.go$
    threshold: 0.0

  - path: ^pkg/lobperformance/db2_helper.go$
    threshold: 0.0
  - path: ^pkg/lobperformance/gen.go$
  - path: ^pkg/lobperformance/lobplan.go$
    threshold: 0.0
  - path: ^pkg/lobperformance/pg_helper.go$
    threshold: 0.0
  - path: ^pkg/lobperformance/rand_generator.go$
    threshold: 0.0
  - path: ^pkg/lobperformance/stage.go$
    threshold: 0.0
  - path: ^pkg/lobperformance/test_execution.go$
    threshold: 0.0

  - path: ^pkg/ruperformance/main.go$
    threshold: 0.0
  - path: ^pkg/ruperformance/pg_helper.go$
    threshold: 0.0
  - path: ^pkg/ruperformance/db_helper.go$
    threshold: 0.0
  - path: ^pkg/ruperformance/db2_helper.go$
    threshold: 0.0
  - path: ^pkg/ruperformance/gen.go$
    threshold: 0.0
  - path: ^pkg/ruperformance/stage.go$
    threshold: 0.0
  - path: ^pkg/ruperformance/test_execution.go$
    threshold: 0.0
  - path: ^pkg/ruperformance/testmetrics.go$
    threshold: 0.0

  - path: ^pkg/pg/pool.go$
    threshold: 0.0
  - path: ^pkg/db2client$
    threshold: 0.0
  - path: ^pkg/utils$
    threshold: 68
  - path: ^internal/arguments$
    threshold: 0.0
  - path: ^pkg/dbinterface$
    threshold: 0.0
  - path: ^pkg/pg$  
    threshold: 23
  - path: ^pkg/dbclient$
    threshold: 0.0
  - path: ^pkg/lobperformance$
    threshold: 0.0
  - path: ^pkg/ruperformance$
    threshold: 0.0



# Holds regexp rules which will exclude matched files or packages
# from coverage statistics.
exclude:
  # Exclude files or packages matching their paths
  paths:
    - cmd
    - e2e

# File name of go-test-coverage breakdown file, which can be used to
# analyze coverage difference.
breakdown-file-name: ''

diff:
  # File name of go-test-coverage breakdown file which will be used to
  # report coverage difference.
  base-breakdown-file-name: ''
