version: '3.8'

services:
  db2:
    image: icr.io/db2_community/db2
    #hostname: db2
    platform: linux/amd64
    privileged: true
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2fdw
      DBNAME: testdb
    volumes:
      - ./database:/database
  builder:
    image: builder
    environment:
      DB2_HOME: /opt/ibm/db2/V12.1
    build:
      context: docker/builder
      args:
        - PGVERSION=${PGVERSION}
    platform: linux/amd64
    volumes:
      - ./:/host
    command: /scripts/build_rpm.sh
  postgres:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
  pgtwool:
    build:
      context: .
      dockerfile: Dockerfile.pg
    environment:
      PGPASSWORD: postgres
      PGHOST: postgres
      PGUSER: postgres
    # command: ru-performance stage
    # command: ru-performance gen &&
    command: ru-performance test --executionTime 300 --warmupTime 20 --isolationLevel 0
    
