ARG VERSION=v0.0.0

FROM golang:bookworm AS buildstage

WORKDIR /usr/src/app/

COPY go.* /usr/src/app/
COPY cmd /usr/src/app/cmd/
COPY internal /usr/src/app/internal/
COPY pkg /usr/src/app/pkg/

RUN go mod tidy
RUN go build -v -a -ldflags="-X 'github.com/pgvillage-tools/dbtwool/internal/version/main.appVersion=${VERSION}'" -o ./pgtwool ./cmd/pgtwool

FROM debian:bookworm

COPY --from=buildstage /usr/src/app/pgtwool /pgtwool

ENTRYPOINT ["/pgtwool"]
